### ISSUE TITLE
Deployment fails with simple-git version 1.64.0, need to lock down version number

### ISSUE THREAD

**Issue by rsullivan00** [ember-cli-deploy/ember-cli-deploy-revision-data#47]
Running a deploy using git on a fresh install will fail with `TypeError: path must be a string or Buffer`. This is fixed by specifying the exact simple-git version in `package.json`:

```
"simple-git": "^1.47.0" -> "simple-git": "1.47.0"
```
**Versions**
simple-git: 1.64.0
ember-cli-deploy-revision-data: 0.3.0

Error from `ember deploy staging --activate --verbose`:
```
+- prepare
|  |
|  +- revision-data
- creating revision data using `file-hash`
- TypeError: path must be a string or Buffer
|
+- didFail
TypeError: path must be a string or Buffer
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.statSync (fs.js:987:18)
    at FSMonitor._measure (/Users/rsullivan/Desktop/my-app/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/Users/rsullivan/Desktop/my-app/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at exists (/Users/rsullivan/Desktop/my-app/node_modules/ember-cli-deploy-revision-data/node_modules/simple-git/src/util/exists.js:7:21)
    at module.exports (/Users/rsullivan/Desktop/my-app/node_modules/ember-cli-deploy-revision-data/node_modules/simple-git/src/util/exists.js:28:11)
    at module.exports (/Users/rsullivan/Desktop/my-app/node_modules/ember-cli-deploy-revision-data/node_modules/simple-git/src/index.js:10:21)
    at /Users/rsullivan/Desktop/my-app/node_modules/ember-cli-deploy-revision-data/lib/scm-data-generators/git.js:17:7
    at initializePromise (/Users/rsullivan/Desktop/my-app/node_modules/rsvp/dist/rsvp.js:588:5)
```

**Comment by ghedamat** [comment]
@Rsullivan00 , sorry I'm a bit late here

should we still lock then or was this related to https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/48

**Comment by rsullivan00** [comment]
Oh yeah this should be closed also. Details on how I got around the issue are in https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/48

**Comment by ghedamat** [comment]
cool! thanks!
